source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails'
gem 'pg'
gem 'jsonapi-resources'
gem 'rack-cors', :require => 'rack/cors'
gem 'jquery-rails'
gem 'turbolinks'
gem 'sinatra', require: false
gem 'slim'

group :development do
  gem 'guard-rspec', require: false
end

group :development, :test do
  gem 'faker'
  gem 'rspec-rails'
  gem 'factory_girl_rails', :require => false
  gem 'httplog'
  gem 'byebug'
end

group :test do
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'shoulda-matchers', '~> 3.0'
end
